services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=latte
      - DB_PASSWORD=latte
      - DB_NAME=order-providing-system
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs  # Mount the logs directory

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=latte
      - POSTGRES_PASSWORD=latte
      - POSTGRES_DB=order-providing-system
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./migrations/insert.sql:/docker-entrypoint-initdb.d/insert.sql